# Neo4j Configuration
neo4j_url: "bolt://localhost:7687"
neo4j_user: "neo4j"
neo4j_password: "password"

# Chunking Configuration
chunk_size: 1024
chunk_overlap: 0
separators:
  - "</p>"
  - "</div>"
  - "</section>"
  - "</h1>"
  - "</h2>"
  - "</h3>"
  - "<br>"
  - ". "
  - "\n\n"
  - "\n"
  - " "
  - ""

# Embedding Configuration
embed_model: "BAAI/bge-small-en-v1.5" # "text-embedding-ada-002"
batch_size: 128

# LLM Configuration
llm_model: "claude-3-sonnet-20240229" # "gpt-3.5-turbo"
top_k: 5