version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=none
      - NEO4JLABS_PLUGINS=["graph-data-science"]
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data:/data